### ISSUE TITLE
Two robot_pose_ekf launches installed by default. 

### ISSUE THREAD

**Issue by pmukherj** [husky/husky_bringup#2]
navsat_config should be optional and not default in husky-core start. even if /dev/clearpth/gps is detected.

install script will need to be updated.

**Comment by mikepurvis** [comment]
This was resolved by c7aa678f8454327e08cdabbdb37b312326afb9c5; the user now configures manually whether the EKF includes GPS by editing the /etc/ros/husky_ekf.yaml configuration file.
